ACCOUNT_INFO_FILE: tomic/data/account_info.json
AMOUNT_REGULARS: 3
AMOUNT_WEEKLIES: 0
BID_ASK_TIMEOUT: 3
CONTRACT_DETAILS_RETRIES: 2
CONTRACT_DETAILS_TIMEOUT: 4
DEFAULT_SYMBOLS:
- AAPL
- AMD
- AMZN
- BAC
- BA
- COST
- CRM
- DIA
- EEM
- GLD
- GOOGL
- HYG
- IWM
- JPM
- LULU
- META
- MSFT
- NFLX
- NVDA
- ORCL
- QQQ
- SLV
- SPY
- TLT
- TSLA
- USO
- XLE
- XLF
- XLI
- XLU
DELTA_MAX: 1.0
DELTA_MIN: -1.0
DOWNLOAD_RETRIES: 3
DOWNLOAD_TIMEOUT: 10
EXPORT_DIR: exports
FIRST_EXPIRY_MIN_DTE: 3
HIST_BARSIZE: 1 day
HIST_DURATION: 1 D
HIST_WHAT: TRADES
IB_CLIENT_ID: 100
IB_HOST: 127.0.0.1
IB_PORT: 7497
INCLUDE_GREEKS_ONLY_IF_MARKET_OPEN: true
INTEREST_RATE: 0.05
JOURNAL_FILE: tomic/data/journal.json
LOG_LEVEL: DEBUG
MARKET_DATA_TIMEOUT: 180
MAX_CONCURRENT_REQUESTS: 8
MKT_GENERIC_TICKS: 100,101,106
OPTIONS_EXCHANGE: SMART
OPTIONS_PRIMARY_EXCHANGE: ''
OPTION_DATA_RETRIES: 3
OPTION_RETRY_WAIT: 1
OPTION_PARAMS_TIMEOUT: 20
PORTFOLIO_META_FILE: tomic/data/portfolio_meta.json
POSITIONS_FILE: tomic/data/positions.json
STRIKE_RANGE: 3
STRIKE_STDDEV_MULTIPLIER: 1.0
UNDERLYING_EXCHANGE: SMART
UNDERLYING_PRIMARY_EXCHANGE: ARCA
USE_HISTORICAL_IV_WHEN_CLOSED: true
VOLATILITY_DATA_FILE: tomic/data/volatility_data.json
PRICE_HISTORY_DIR: tomic/data/spot_prices
IV_HISTORY_DIR: tomic/data/iv_history
IV_DAILY_SUMMARY_DIR: tomic/data/iv_daily_summary
HISTORICAL_VOLATILITY_DIR: tomic/data/historical_volatility
IV_TRACKING_DELTAS:
- 0.25
- 0.5
IV_EXPIRY_LOOKAHEAD_DAYS:
- 0
- 30
- 60
