ACCOUNT_INFO_FILE: tomic/data/account_info.json
AMOUNT_REGULARS: 3
AMOUNT_WEEKLIES: 0
BID_ASK_TIMEOUT: 5
CONTRACT_DETAILS_RETRIES: 2
CONTRACT_DETAILS_TIMEOUT: 30
DEFAULT_SYMBOLS:
- AAPL
- CRM
- DIA
- EEM
- GLD
- IWM
- MSFT
- NVDA
- QQQ
- SPY
- TLT
- TSLA
- XLE
- XLF
- XLI
- XLY
DELTA_MAX: 0.8
DELTA_MIN: -0.8
DOWNLOAD_RETRIES: 2
DOWNLOAD_TIMEOUT: 30
EXPORT_DIR: exports
IB_CLIENT_ID: 100
IB_HOST: 127.0.0.1
IB_PORT: 7497
INCLUDE_GREEKS_ONLY_IF_MARKET_OPEN: true
INTEREST_RATE: 0.05
JOURNAL_FILE: tomic/data/journal.json
LOG_LEVEL: INFO
MARKET_DATA_TIMEOUT: 120
MAX_CONCURRENT_REQUESTS: 10
OPTIONS_EXCHANGE: SMART
OPTIONS_PRIMARY_EXCHANGE: CBOE
OPTION_DATA_RETRIES: 0
OPTION_RETRY_WAIT: 1
PORTFOLIO_META_FILE: tomic/data/portfolio_meta.json
POSITIONS_FILE: tomic/data/positions.json
PRIMARY_EXCHANGE: SMART
STRIKE_RANGE: 5
UNDERLYING_EXCHANGE: SMART
UNDERLYING_PRIMARY_EXCHANGE: ARCA
USE_HISTORICAL_IV_WHEN_CLOSED: true
VOLATILITY_DATA_FILE: tomic/data/volatility_data.json
VOLATILITY_DB: data/volatility.db
