ACCOUNT_INFO_FILE: tomic/data/account_info.json
AMOUNT_REGULARS: 3
AMOUNT_WEEKLIES: 3
BID_ASK_TIMEOUT: 20
CONTRACT_DETAILS_RETRIES: 4
CONTRACT_DETAILS_TIMEOUT: 10
DATA_PROVIDER: ib
DEFAULT_SYMBOLS:
- AAPL
- ABBV
- AEP
- AMD
- AMGN
- AMT
- AMZN
- AXP
- BA
- BAC
- BMY
- C
- CAT
- CL
- COST
- CRM
- CVS
- CVX
- D
- DE
- DLR
- DIA
- EEM
- ED
- EOG
- ESS
- EXC
- GE
- GLD
- GILD
- GOOGL
- GS
- HAL
- HD
- HON
- IWM
- INTC
- JNJ
- JPM
- KMB
- KO
- KR
- LOW
- LMT
- LULU
- MA
- MCD
- META
- MMM
- MO
- MRK
- MS
- MSFT
- MU
- NEE
- NFLX
- NKE
- NOC
- NVDA
- ORCL
- OXY
- PEP
- PFE
- PG
- PM
- PXD
- QQQ
- ROST
- SBUX
- SCHW
- SLB
- SLV
- SO
- SPG
- SPY
- TGT
- TLT
- TSLA
- UNH
- UNP
- UPS
- USO
- V
- VLO
- WFC
- WMT
- XEL
- XOM
DELTA_MAX: 1
DELTA_MIN: -1
DOWNLOAD_RETRIES: 3
DOWNLOAD_TIMEOUT: 10
EXPORT_DIR: exports
FIRST_EXPIRY_MIN_DTE: 15
HISTORICAL_VOLATILITY_DIR: tomic/data/historical_volatility
HIST_BARSIZE: 1 day
HIST_DURATION: 1 D
HIST_WHAT: TRADES
IB_CLIENT_ID: 100
IB_HOST: 127.0.0.1
IB_PORT: 7497
INCLUDE_GREEKS_ONLY_IF_MARKET_OPEN: true
INTEREST_RATE: 0.05
IV_DAILY_SUMMARY_DIR: tomic/data/iv_daily_summary
IV_DEBUG_DIR: iv_debug
IV_EXPIRY_LOOKAHEAD_DAYS:
- 0
- 30
- 60
IV_HISTORY_DIR: tomic/data/iv_history
IV_TRACKING_DELTAS:
- 0.25
- 0.5
JOURNAL_FILE: tomic/data/journal.json
LOG_LEVEL: INFO
MARKET_DATA_TIMEOUT: 180
MAX_CONCURRENT_REQUESTS: 5
MAX_SYMBOLS_PER_RUN: null
MKT_GENERIC_TICKS: 100,101,106
OPTIONS_EXCHANGE: SMART
OPTIONS_PRIMARY_EXCHANGE: ''
OPTION_DATA_RETRIES: 5
OPTION_MAX_MARKETDATA_TIME: 240
OPTION_PARAMS_TIMEOUT: 20
OPTION_RETRY_WAIT: 2
POLYGON_API_KEY: ''
POLYGON_API_KEYS:
- RsrPUtvYFnrxOlyLesJZoTMVpnexUimm
- C1mMXJKp26BchVt4nK6nkx75PL3ZZ8nh
- 76XfeYzekKewGBLVge22DmSH6zDI57za
- qWzywQGs3Lw4fIEEfRSadAvKSLQUM3Gk
- uwiW1MK9zLZ9PDS6I6tCYNmNMOE27QI_
POLYGON_DELAY_SNAPSHOT_MS: 200
POLYGON_SLEEP_BETWEEN: 1.2
PORTFOLIO_META_FILE: tomic/data/portfolio_meta.json
PRICE_META_FILE: tomic/data/price_meta.json
POSITIONS_FILE: tomic/data/positions.json
PRICE_HISTORY_DIR: tomic/data/spot_prices
SCORE_WEIGHT_EV: 0.2
SCORE_WEIGHT_POS: 0.3
SCORE_WEIGHT_ROM: 0.5
STRIKE_RANGE: 30
STRIKE_STDDEV_MULTIPLIER: 2.5
UNDERLYING_EXCHANGE: SMART
UNDERLYING_PRIMARY_EXCHANGE: ARCA
USE_HISTORICAL_IV_WHEN_CLOSED: true
