ACCOUNT_INFO_FILE: tomic/data/account_info.json
AMOUNT_REGULARS: 1
AMOUNT_WEEKLIES: 0
BID_ASK_TIMEOUT: 5
CONTRACT_DETAILS_RETRIES: 2
CONTRACT_DETAILS_TIMEOUT: 4
DEFAULT_SYMBOLS:
- AAPL
- CRM
- DIA
- EEM
- GLD
- IWM
- MSFT
- NVDA
- QQQ
- SPY
- TLT
- TSLA
- XLE
- XLF
- XLI
- XLY
DELTA_MAX: 1.0
DELTA_MIN: -1.0
DOWNLOAD_RETRIES: 2
DOWNLOAD_TIMEOUT: 5
EXPORT_DIR: exports
FIRST_EXPIRY_MIN_DTE: 15
IB_CLIENT_ID: 100
IB_HOST: 127.0.0.1
IB_PORT: 7497
INCLUDE_GREEKS_ONLY_IF_MARKET_OPEN: true
INTEREST_RATE: 0.05
JOURNAL_FILE: tomic/data/journal.json
LOG_LEVEL: DEBUG
MARKET_DATA_TIMEOUT: 15
MAX_CONCURRENT_REQUESTS: 5
OPTIONS_EXCHANGE: SMART
OPTIONS_PRIMARY_EXCHANGE: ''
OPTION_DATA_RETRIES: 2
OPTION_RETRY_WAIT: 3
PORTFOLIO_META_FILE: tomic/data/portfolio_meta.json
POSITIONS_FILE: tomic/data/positions.json
STRIKE_RANGE: 5
UNDERLYING_EXCHANGE: SMART
UNDERLYING_PRIMARY_EXCHANGE: ARCA
USE_HISTORICAL_IV_WHEN_CLOSED: true
VOLATILITY_DATA_FILE: tomic/data/volatility_data.json
VOLATILITY_DB: data/volatility.db
