ACCOUNT_INFO_FILE: account_info.json
DEFAULT_SYMBOLS:
- AAPL
- ASML
- CRM
- DIA
- EEM
- EWJ
- EWG
- EWZ
- FEZ
- FXE
- FXI
- GLD
- INDA
- IWM
- NVDA
- QQQ
- SPY
- TSLA
- TLT
- VIX
- XLE
- XLF
- XLI
- XLK
- XLV
- XLY
EXPORT_DIR: exports
IB_HOST: 127.0.0.1
IB_PORT: 7497
INTEREST_RATE: 0.05
JOURNAL_FILE: journal.json
LOG_LEVEL: DEBUG
PORTFOLIO_META_FILE: portfolio_meta.json
POSITIONS_FILE: positions.json
VOLATILITY_DATA_FILE: volatility_data.json
