ACCOUNT_INFO_FILE: tomic/data/account_info.json
AMOUNT_REGULARS: 3
AMOUNT_WEEKLIES: 4
WEEKLY_EXPIRIES_MIN_DTE: 15
BID_ASK_TIMEOUT: 20
CONTRACT_DETAILS_RETRIES: 4
CONTRACT_DETAILS_TIMEOUT: 10
DATA_PROVIDER: ib
DEFAULT_SYMBOLS:
- AAPL
- AMD
- AMZN
- BA
- BAC
- COST
- CRM
- DIA
- EEM
- GLD
- GOOGL
- IWM
- JPM
- LULU
- META
- MSFT
- NFLX
- NVDA
- ORCL
- QQQ
- SLV
- SPY
- TLT
- TSLA
- USO
- XLE
- XLF
DELTA_MAX: 0.8
DELTA_MIN: -0.8
DOWNLOAD_RETRIES: 3
DOWNLOAD_TIMEOUT: 10
EXPORT_DIR: exports
FIRST_EXPIRY_MIN_DTE: 15
FLATFILE_DIR: tomic/data/flatfiles
HISTORICAL_VOLATILITY_DIR: tomic/data/historical_volatility
HIST_BARSIZE: 1 day
HIST_DURATION: 1 D
HIST_WHAT: TRADES
IB_CLIENT_ID: 100
IB_HOST: 127.0.0.1
IB_PORT: 7497
INCLUDE_GREEKS_ONLY_IF_MARKET_OPEN: true
INTEREST_RATE: 0.05
IV_DAILY_SUMMARY_DIR: tomic/data/iv_daily_summary
IV_DEBUG_DIR: iv_debug
IV_EXPIRY_LOOKAHEAD_DAYS:
- 0
- 30
- 60
IV_HISTORY_DIR: tomic/data/iv_history
IV_TRACKING_DELTAS:
- 0.25
- 0.5
JOURNAL_FILE: tomic/data/journal.json
LOG_LEVEL: DEBUG
MARKET_DATA_TIMEOUT: 180
MAX_CONCURRENT_REQUESTS: 5
MAX_SYMBOLS_PER_RUN: null
MKT_GENERIC_TICKS: 100,101,106
OPTIONS_EXCHANGE: SMART
OPTIONS_PRIMARY_EXCHANGE: ''
OPTION_DATA_RETRIES: 5
OPTION_MAX_MARKETDATA_TIME: 240
OPTION_PARAMS_TIMEOUT: 20
OPTION_RETRY_WAIT: 2
POLYGON_API_KEY: ''
POLYGON_API_KEYS:
- RsrPUtvYFnrxOlyLesJZoTMVpnexUimm
- C1mMXJKp26BchVt4nK6nkx75PL3ZZ8nh
- 76XfeYzekKewGBLVge22DmSH6zDI57za
- qWzywQGs3Lw4fIEEfRSadAvKSLQUM3Gk
- uwiW1MK9zLZ9PDS6I6tCYNmNMOE27QI_
POLYGON_DELAY_SNAPSHOT_MS: 200
POLYGON_SLEEP_BETWEEN: 1.2
PORTFOLIO_META_FILE: tomic/data/portfolio_meta.json
POSITIONS_FILE: tomic/data/positions.json
PRICE_HISTORY_DIR: tomic/data/spot_prices
STRIKE_RANGE: 30
STRIKE_STDDEV_MULTIPLIER: 2.5
UNDERLYING_EXCHANGE: SMART
UNDERLYING_PRIMARY_EXCHANGE: ARCA
USE_HISTORICAL_IV_WHEN_CLOSED: true
