ACCOUNT_INFO_FILE: tomic/data/account_info.json
AMOUNT_REGULARS: 1
AMOUNT_WEEKLIES: 0
CONTRACT_DETAILS_RETRIES: 0
CONTRACT_DETAILS_TIMEOUT: 2
DEFAULT_SYMBOLS:
- AAPL
- CRM
- DIA
- EEM
- GLD
- IWM
- MSFT
- NVDA
- QQQ
- SPY
- TLT
- TSLA
- VIX
- XLE
- XLF
- XLI
- XLY
DELTA_MAX: 0.8
DELTA_MIN: 0.3
DOWNLOAD_RETRIES: 2
DOWNLOAD_TIMEOUT: 10
EXPORT_DIR: exports
IB_HOST: 127.0.0.1
IB_PORT: 7497
IB_CLIENT_ID: 100
INTEREST_RATE: 0.05
JOURNAL_FILE: tomic/data/journal.json
LOG_LEVEL: DEBUG
MAX_CONCURRENT_REQUESTS: 10
PORTFOLIO_META_FILE: tomic/data/portfolio_meta.json
POSITIONS_FILE: tomic/data/positions.json
PRIMARY_EXCHANGE: SMART
STRIKE_RANGE: 1
VOLATILITY_DATA_FILE: tomic/data/volatility_data.json
