ACCOUNT_INFO_FILE: tomic/data/account_info.json
CONTRACT_DETAILS_RETRIES: 0
CONTRACT_DETAILS_TIMEOUT: 2
DEFAULT_SYMBOLS:
- AAPL
- QQQ
- GLD
DELTA_MAX: 0.8
DELTA_MIN: -0.8
DOWNLOAD_RETRIES: 2
DOWNLOAD_TIMEOUT: 10
EXPORT_DIR: exports
IB_HOST: 127.0.0.1
IB_PORT: 7497
INTEREST_RATE: 0.05
JOURNAL_FILE: tomic/data/journal.json
LOG_LEVEL: INFO
MAX_CONCURRENT_REQUESTS: 10
PORTFOLIO_META_FILE: tomic/data/portfolio_meta.json
POSITIONS_FILE: tomic/data/positions.json
PRIMARY_EXCHANGE: SMART
STRIKE_RANGE: 10
AMOUNT_REGULARS: 3
AMOUNT_WEEKLIES: 4
VOLATILITY_DATA_FILE: tomic/data/volatility_data.json
