DEFAULT_SYMBOLS:
  - SPY
  - QQQ
  - DIA
  - GLD
  - TSLA
  - AAPL
  - CRM
  - XLF
  - XLE
POSITIONS_FILE: positions.json
ACCOUNT_INFO_FILE: account_info.json
JOURNAL_FILE: journal.json
VOLATILITY_DATA_FILE: volatility_data.json
EXPORT_DIR: exports
IB_HOST: 127.0.0.1
IB_PORT: 7497
