name: Fetch Polygon IV

on:
  schedule:
    - cron: '5 19 * * 1-5'
  workflow_dispatch:

jobs:
  fetch-iv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run Polygon IV fetcher
        run: |
          python -m tomic.cli.fetch_iv_polygon

      - name: Commit and push changes
        run: |
          git status --short
          if [ -n "$(git status --porcelain)" ]; then
            git add tomic/data/iv_daily_summary/*.json
            git commit -m "Update Polygon IV data"
            git push
          else
            echo "No changes to commit"
          fi
